<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/helpers.php';
require_admin();
$user=$_SESSION['pending_admin_face_user']??null;
$created=(int)($_SESSION['pending_admin_face_created']??0);
if(!$user || !$created || time()-$created>900){ unset($_SESSION['pending_admin_face_user'],$_SESSION['pending_admin_face_created']); redirect('/modules/system_admin_security/index.php'); }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Face ID Registration — Core Transaction 4</title><link rel="stylesheet" href="../style.css"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&family=Material+Symbols+Outlined:FILL@0..1&display=swap" rel="stylesheet"><style>
.faceid-panel{display:flex;flex-direction:column;align-items:center;gap:14px}.faceid-camera{width:min(320px,100%);aspect-ratio:4/3;border-radius:22px;background:#17122b;border:1px solid #ddd6fe;overflow:hidden;position:relative;box-shadow:0 18px 40px rgba(76,29,149,.16)}.faceid-camera video{width:100%;height:100%;object-fit:cover;transform:scaleX(-1);display:block}.faceid-ring{position:absolute;inset:14% 22%;border:3px solid rgba(255,255,255,.9);border-radius:48% 48% 44% 44%;box-shadow:0 0 0 999px rgba(49,46,129,.14);pointer-events:none}.faceid-status{width:100%;text-align:center;font-size:13px;line-height:1.5;color:#6b6680}.faceid-status strong{color:#4c1d95}.faceid-steps{width:100%;display:grid;gap:8px;margin:4px 0}.faceid-step{display:flex;align-items:center;gap:9px;padding:9px 11px;border:1px solid #e4ddf4;border-radius:11px;background:#faf9ff;color:#6b6680;font-size:12px}.faceid-step .material-symbols-outlined{font-size:18px;color:#7c3aed}.faceid-step.done{border-color:#c4b5fd;background:#f5f3ff;color:#4c1d95}.faceid-error{display:none;width:100%;text-align:center}.faceid-note{font-size:11px;color:#756b8d;text-align:center;line-height:1.5}
</style></head><body class="auth-body"><div class="login-page"><div class="login-card auth-card"><div class="brand-mark auth-brand"><div class="brand-logo-white auth-logo-wrap"><img src="../assets/logo2.svg" alt="Great Solomon Manpower Services Inc. logo" class="brand-logo-image"></div><div class="auth-brand-copy"><strong>Great Solomon Manpower Services Inc.</strong><div class="small-muted">Core Transaction 4</div></div></div><div class="auth-heading"><span class="material-symbols-outlined">face</span><h1>Register Face ID</h1><p>Administrator account creation requires a Face ID enrollment before the new account can be activated.</p></div><div class="faceid-panel"><div class="notice success" style="width:100%;box-sizing:border-box"><strong><?=e($user['name'])?></strong><br><?=e($user['email'])?> · <?=e($user['role'])?></div><div class="faceid-camera"><video id="faceVideo" autoplay muted playsinline></video><div class="faceid-ring"></div></div><div class="faceid-status" id="faceStatus"><strong>Camera permission required.</strong> Allow camera access, center one face, keep your eyes open, then blink once.</div><div class="faceid-steps"><div class="faceid-step" id="stepFace"><span class="material-symbols-outlined">person_search</span><span>One face detected</span></div><div class="faceid-step" id="stepBlink"><span class="material-symbols-outlined">visibility</span><span>Blink once to pass liveness check</span></div><div class="faceid-step" id="stepConfirm"><span class="material-symbols-outlined">face</span><span>Confirm with Face ID</span></div></div><div class="notice error faceid-error" id="faceError"></div><button class="gw-btn primary auth-submit" type="button" id="faceButton" disabled><span class="material-symbols-outlined">face</span> Confirm with Face ID</button><a class="auth-link secondary" href="../modules/system_admin_security/index.php">Cancel and return to User Accounts</a><div class="faceid-note">The camera blink check is an application liveness step. The actual Face ID biometric remains protected by the user's device; CT4 stores only the WebAuthn public credential.</div></div></div></div><script src="https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/face_mesh.js"></script><script>
(function(){const csrf=<?=json_encode(csrf_token())?>,button=document.getElementById('faceButton'),status=document.getElementById('faceStatus'),errorBox=document.getElementById('faceError');let processing=false,lastClosed=false,openFrames=0,closeFrames=0,stream=null,mesh=null;
function err(m){errorBox.textContent=m;errorBox.style.display='block';status.innerHTML='<strong>Face ID could not continue.</strong> '+m} function step(id,done){document.getElementById(id)?.classList.toggle('done',done)} function b64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a} function enc(a){let s='';a=new Uint8Array(a);for(const x of a)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')} async function call(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf},credentials:'same-origin',body:JSON.stringify(body)});const j=await r.json().catch(()=>({ok:false,error:'Unexpected server response.'}));if(!r.ok||!j.ok)throw new Error(j.error||'Face ID request failed.');return j}
function norm(o){o.challenge=b64(o.challenge);o.user.id=b64(o.user.id);(o.excludeCredentials||[]).forEach(c=>c.id=b64(c.id));return o}
async function confirm(){if(processing)return;processing=true;button.disabled=true;errorBox.style.display='none';try{if(!window.PublicKeyCredential)throw new Error('This browser does not support Face ID / passkeys. Use a modern HTTPS browser on a device with Face ID.');const o=norm((await call('biometric_admin_register_options.php',{})).options);const cred=await navigator.credentials.create({publicKey:o});if(!cred)throw new Error('Face ID enrollment was cancelled.');const r=cred.response;await call('biometric_admin_register.php',{id:cred.id,rawId:enc(cred.rawId),type:cred.type,response:{clientDataJSON:enc(r.clientDataJSON),attestationObject:enc(r.attestationObject)}});window.location.href='../modules/system_admin_security/index.php?face_registered=1#user-accounts';}catch(e){err(e.message||'Face ID could not be completed.');processing=false;button.disabled=false}}
button.addEventListener('click',confirm);const video=document.getElementById('faceVideo');function ear(lm,a,b,c,d,e,f){const p=i=>({x:lm[i].x,y:lm[i].y}),d2=(x,y)=>Math.hypot(x.x-y.x,x.y-y.y);return(d2(p(b),p(f))+d2(p(c),p(e)))/(2*d2(p(a),p(d))+.0001)} async function start(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=stream;await video.play();if(typeof FaceMesh==='undefined')throw new Error('The liveness component could not load.');mesh=new FaceMesh({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh@0.4.1633559619/${f}`});mesh.setOptions({maxNumFaces:1,refineLandmarks:true,minDetectionConfidence:.6,minTrackingConfidence:.6});mesh.onResults(r=>{if(!r.multiFaceLandmarks||r.multiFaceLandmarks.length!==1){openFrames=0;closeFrames=0;status.innerHTML='<strong>Center your face.</strong> Make sure exactly one face is visible.';return}step('stepFace',true);const lm=r.multiFaceLandmarks[0],v=(ear(lm,33,160,158,133,153,144)+ear(lm,362,385,387,263,373,380))/2;if(v>.22){openFrames++;if(lastClosed&&openFrames>=2){step('stepBlink',true);step('stepConfirm',true);button.disabled=false;status.innerHTML='<strong>Blink confirmed.</strong> You can now tap Confirm with Face ID.'}}if(v<.17&&openFrames>=2){closeFrames++;if(closeFrames>=2){lastClosed=true;openFrames=0;status.innerHTML='<strong>Blink detected.</strong> Open your eyes again to continue.'}}if(v>=.17)closeFrames=0});(async function loop(){if(video.readyState>=2&&!processing)await mesh.send({image:video});requestAnimationFrame(loop)})()}catch(e){err(e.message);button.disabled=true}}start();addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));})();</script><script src="../app.js"></script></body></html>
