<?php
require_once __DIR__.'/../../includes/helpers.php'; require_once __DIR__.'/../../includes/service_client.php'; require_login(); $svc=service('assets');
if($_SERVER['REQUEST_METHOD']==='POST'){try{$message=$svc->handle((string)($_POST['action']??''),$_POST,current_user());flash('success',$message);}catch(Throwable $e){flash('error','Unable to save record: '.$e->getMessage());}redirect('/modules/asset_equipment/index.php');}
$assets=$svc->assets(); $issuances=$svc->issuances(); $currentRole=(string)(current_user()['role']??''); $canChangeStatus=in_array($currentRole,['Administrator','Warehouse'],true);
page_header('Asset & Equipment Issuance','assets');show_flash();?><div class="gw-breadcrumb"><span>Great Solomon Manpower Services Inc.</span><span>/</span><strong>Asset &amp; Equipment Issuance</strong></div><section class="gw-hero"><div><div class="eyebrow">MODULE 4</div><h1>Asset &amp; Equipment Issuance Tracker</h1><p>Track equipment issuance, returns and maintenance.</p></div></section><section class="gw-quick-actions"><a href="#issue"><span class="material-symbols-outlined">assignment_turned_in</span> Issue / Return</a><a href="#available-items"><span class="material-symbols-outlined">inventory_2</span> Available Items</a><a href="#issuance-history"><span class="material-symbols-outlined">build</span> Issuance History</a></section><section class="gw-stats"><div class="gw-stat"><span class="gw-stat-label">Total Assets</span><div class="gw-stat-value"><?=count($assets)?></div><div class="gw-stat-meta">Asset registry</div></div><div class="gw-stat"><span class="gw-stat-label">Issued</span><div class="gw-stat-value"><?=count(array_filter($assets,fn($a)=>$a['status']==='Issued'))?></div><div class="gw-stat-meta">Currently assigned</div></div><div class="gw-stat"><span class="gw-stat-label">Maintenance</span><div class="gw-stat-value"><?=count(array_filter($assets,fn($a)=>$a['status']==='Maintenance'))?></div><div class="gw-stat-meta warning">Needs service</div></div></section>
<section class="record-form" id="issue"><div class="gw-panel-head"><h2>Issue Equipment</h2><span>Assign an available registered asset.</span></div><form method="post"><input type="hidden" name="action" value="issue_asset"><div class="form-grid"><div><label>Asset</label><select name="asset_id" required><option value="">Select available asset</option><?php foreach($assets as $a): if(($a['status']??'')==='Available' && (int)$a['available_quantity']>0):?><option value="<?=$a['id']?>"><?=e($a['asset_tag'].' — '.$a['name'])?> (<?=e($a['available_quantity'])?> available)</option><?php endif; endforeach;?></select></div><div><label>Employee</label><input name="employee_name" required></div><div><label>Issued Date</label><input type="date" name="issued_date" required value="<?=date('Y-m-d')?>"></div><div><label>Expected Return</label><input type="date" name="expected_return"></div><div class="full"><label>Notes</label><textarea name="notes"></textarea></div></div><div class="record-actions"><button class="gw-btn primary">Issue Equipment</button></div></form></section>
<section class="gw-panel" id="available-items" style="margin-top:20px"><div class="gw-panel-head"><h2>Available Items</h2><span>Current asset availability</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Picture</th><th>Name</th><th>Serial No.</th><th>Units Available</th><th>Status</th><th>Picture Action</th></tr></thead><tbody><?php foreach($assets as $a): $available=(int)($a['available_quantity']??0); ?><tr>
<td><?php if(!empty($a['image_data'])): ?><button type="button" class="asset-picture-thumb" onclick="showAssetPicture(<?= (int)$a['id'] ?>, <?=json_encode((string)$a['name'],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP)?>)" title="View asset picture"><img src="<?=e(url('/modules/asset_equipment/asset_image.php?id='.(int)$a['id']))?>" alt="<?=e($a['name'])?>"></button><?php else: ?><span class="asset-picture-placeholder">No picture</span><?php endif; ?></td>
<td><?=e($a['name'])?></td><td><?=e($a['serial_number']??'—')?></td><td><?=e($available)?></td><td><?=e($a['status']??'—')?></td>
<td><form method="post" enctype="multipart/form-data" class="asset-picture-form"><input type="hidden" name="action" value="update_asset_picture"><input type="hidden" name="asset_id" value="<?= (int)$a['id'] ?>"><label class="gw-btn ghost asset-picture-upload"> <?=!empty($a['image_data'])?'Change':'Add'?> Picture<input type="file" name="asset_image" accept="image/jpeg,image/png,image/webp,image/gif" onchange="this.form.submit()" hidden></label></form></td>
</tr><?php endforeach;if(!$assets):?><tr><td colspan="6" class="empty">No items available.</td></tr><?php endif;?></tbody></table></div></section>
<section class="gw-panel" id="issuance-history" style="margin-top:20px"><div class="gw-panel-head"><h2>Issuance History</h2><span><?=count($issuances)?> records</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Asset</th><th>Employee</th><th>Issued</th><th>Expected Return</th><th>Status</th><th>Notes</th><?php if($canChangeStatus):?><th>Action</th><?php endif;?></tr></thead><tbody><?php foreach($issuances as $r):?><tr><td><?=e($r['asset_tag'].' — '.$r['name'])?></td><td><?=e($r['employee_name'])?></td><td><?=e($r['issued_date'])?></td><td><?=e($r['expected_return'])?></td><td><?=e($r['status'])?></td><td><?=e($r['notes'])?></td><?php if($canChangeStatus):?><td><form method="post"><input type="hidden" name="action" value="update_issuance_status"><input type="hidden" name="issuance_id" value="<?=$r['id']?>"><select name="status" onchange="this.form.submit()"><option value="Issued" <?=$r['status']==='Issued'?'selected':''?>>Issued</option><option value="Returned" <?=$r['status']==='Returned'?'selected':''?>>Returned</option><option value="Overdue" <?=$r['status']==='Overdue'?'selected':''?>>Overdue</option><option value="Not Returned" <?=$r['status']==='Not Returned'?'selected':''?>>Not Returned</option></select></form></td><?php endif;?></tr><?php endforeach;if(!$issuances):?><tr><td colspan="<?= $canChangeStatus ? 7 : 6 ?>" class="empty">No issuance records.</td></tr><?php endif;?></tbody></table></div></section><?php page_footer(); ?>

<script>
function showAssetPicture(assetId, assetName){
 const root=document.getElementById('modalRoot'); if(!root)return;
 const src=<?=json_encode(url('/modules/asset_equipment/asset_image.php'))?>+'?id='+encodeURIComponent(String(assetId));
 root.innerHTML='<div class="gw-modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="gw-modal" style="width:min(900px,100%)"><div class="gw-modal-head"><div><strong>'+escapeHtml(assetName||'Asset Picture')+'</strong><small>Asset / equipment picture</small></div><button class="gw-modal-close" onclick="closeModal()">×</button></div><div class="gw-modal-body" style="text-align:center"><img src="'+src+'" alt="'+escapeHtml(assetName||'Asset Picture')+'" style="max-width:100%;max-height:70vh;object-fit:contain;border-radius:12px"></div></div></div>';
}
</script>
